version: "3"

services:
  backend:
    build: ./backend
    command: npm start
    ports:
      - "4200:4200"
    restart: always    
  frontend:
    build: ./frontend
    depends_on:
      - "backend"
    ports:
      - "8080:8080"