version: "3"

services:
  backendserver:
    build: ./backend/
    ports:
    - "8080:8080"
  restart: always
  frontend:
  build: ./frontend/
  depends_on:
    - "backendserver"
  ports:
    - "80:80"